services:
  redis:
    image: redis:alpine
    container_name: marketing-redis
    ports:
      - "36379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass "marketing"
    restart: unless-stopped

volumes:
  redis_data:
